// <auto-generated />
using System;
using CoreMultiJoinsProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreMultiJoinsProject.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211214052337_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CoreMultiJoinsProject.Models.Departments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("CoreMultiJoinsProject.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("departmentsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("departmentsId");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("CoreMultiJoinsProject.Models.Employee", b =>
                {
                    b.HasOne("CoreMultiJoinsProject.Models.Departments", "departments")
                        .WithMany()
                        .HasForeignKey("departmentsId");

                    b.Navigation("departments");
                });
#pragma warning restore 612, 618
        }
    }
}
